# Generated by Django 2.1.5 on 2019-02-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minhasimagens',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='minhasimagens'),
        ),
    ]
