# Generated by Django 2.1.5 on 2019-03-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientesunidadesedu',
            name='codesc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escolas.Escolas'),
        ),
    ]
