# Generated by Django 2.1.7 on 2020-04-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.TextField(blank=True, null=True)),
                ('nm_unidade', models.TextField(blank=True, null=True)),
                ('nm_exibicao_unidade', models.TextField(blank=True, null=True)),
                ('tp_unidade_administrativa', models.IntegerField(blank=True, null=True)),
                ('dc_tipo_unidade_administrativa', models.TextField(blank=True, null=True)),
                ('sg_unidade_administrativa', models.TextField(blank=True, null=True)),
                ('cd_unidade_administrativa', models.TextField(blank=True, null=True)),
                ('nm_unidade_administrativa', models.TextField(blank=True, null=True)),
                ('database', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'escolas_ceus',
            },
        ),
    ]
