# Generated by Django 2.1.7 on 2020-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_ceus'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolas',
            name='nomescofi',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
