# Generated by Django 2.1.7 on 2019-03-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dre', models.TextField(blank=True, null=True)),
                ('codes', models.CharField(blank=True, max_length=6, null=True)),
                ('tipoesc', models.CharField(blank=True, max_length=12, null=True)),
                ('nomesc', models.CharField(blank=True, max_length=60, null=True)),
                ('distrito', models.TextField(blank=True, null=True)),
                ('setor', models.SmallIntegerField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('rede', models.TextField(blank=True, null=True)),
                ('modal', models.CharField(blank=True, max_length=100, null=True)),
                ('descserie', models.CharField(blank=True, max_length=100, null=True)),
                ('periodo', models.TextField(blank=True, null=True)),
                ('turno', models.IntegerField(blank=True, null=True)),
                ('descturno', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('idade', models.FloatField(blank=True, null=True)),
                ('nee', models.CharField(blank=True, max_length=100, null=True)),
                ('raca', models.CharField(blank=True, max_length=20, null=True)),
                ('qtd', models.BigIntegerField(blank=True, null=True)),
                ('database', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
