# Generated by Django 2.1.7 on 2026-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidores',
            name='possui_sigilo',
            field=models.BooleanField(default=False),
        ),
    ]
