# Generated by Django 2.1.5 on 2019-02-11 14:26

import debitos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.FloatField(default=0, validators=[debitos.models.validate_floatPositivos])),
                ('status', models.CharField(choices=[('PAGO', 'PAGO'), ('PENDENTE', 'PENDENTE'), ('AGENDADO', 'AGENDADO')], default='PENDENTE', max_length=10)),
            ],
        ),
    ]
