# Generated by Django 2.1.5 on 2019-02-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('horario_func', models.IntegerField()),
                ('idade_minima', models.IntegerField()),
            ],
        ),
    ]
