# Generated by Django 2.1.5 on 2019-02-11 13:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190211_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleo',
            name='month',
            field=models.IntegerField(validators=[core.models.validate_even]),
        ),
    ]
