# Generated by Django 2.1.5 on 2019-02-11 13:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190211_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleo',
            name='month',
            field=models.IntegerField(default=1, validators=[core.models.validate_mes]),
        ),
    ]
