# Generated by Django 2.1.5 on 2019-02-11 14:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190211_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleo',
            name='year',
            field=models.IntegerField(default=2019, validators=[core.models.validate_ano]),
        ),
    ]
