# Generated by Django 2.1.5 on 2019-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
        ('debitos', '0001_initial'),
        ('core', '0005_auto_20190211_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleo',
            name='credits',
            field=models.ManyToManyField(to='creditos.Credits'),
        ),
        migrations.AddField(
            model_name='nucleo',
            name='debts',
            field=models.ManyToManyField(to='debitos.Debts'),
        ),
    ]
