# Generated by Django 2.1.5 on 2019-02-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debitos', '0001_initial'),
        ('creditos', '0001_initial'),
        ('core', '0006_auto_20190211_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nucleo',
            name='credits',
        ),
        migrations.AddField(
            model_name='nucleo',
            name='credits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creditos.Credits'),
        ),
        migrations.RemoveField(
            model_name='nucleo',
            name='debts',
        ),
        migrations.AddField(
            model_name='nucleo',
            name='debts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debitos.Debts'),
        ),
    ]
